export type Locale = "pt" | "en";
export type Theme = "dark" | "light";

export type Dictionary = typeof dictionaries.pt;

export const links = {
  booking: "https://www.lpclinic.pt/marcacoes-online",
  whatsapp: "https://wa.me/351931803555",
  email: "mailto:geral@lpclinic.pt",
  phonePrimary: "tel:+351218287636",
  phoneSecondary: "tel:+351931803555",
  maps: "https://www.google.com/maps/search/?api=1&query=R.+Pinheiros+192B+2750-606+Cascais",
  instagram: "https://www.instagram.com/lpclinic_pt/",
  facebook: "https://www.facebook.com/lpclinicpt/",
  tiktok: "https://www.tiktok.com/@lpclinic_pt",
  dglxss: "https://dglxss.com",
  original: "https://www.lpclinic.pt/",
};

export const RAIL = [
  { id: "sobre", pt: "Sobre", en: "About" },
  { id: "tratamentos", pt: "Tratamentos", en: "Treatments" },
  { id: "tecnologia", pt: "Tecnologia", en: "Technology" },
  { id: "casos", pt: "Casos", en: "Cases" },
  { id: "equipa", pt: "Equipa", en: "Team" },
  { id: "internacional", pt: "Internacional", en: "International" },
  { id: "contacto", pt: "Contacto", en: "Contact" },
] as const;

export const TEAM = [
  { id: "pedro-pimenta", name: "Dr. Pedro Pimenta", role: { pt: "Cirurgia | Reabilitação Oral", en: "Surgery | Oral Rehabilitation" }, photo: "/team/pedro-pimenta.jpg" },
  { id: "catarina-cardoso", name: "Drª Catarina Cardoso", role: { pt: "Harmonização Facial", en: "Facial Harmonization" }, photo: "/team/catarina-cardoso.jpg" },
  { id: "mafalda-faria", name: "Drª Mafalda Faria", role: { pt: "Generalista", en: "General Dentistry" }, photo: "/team/mafalda-faria.jpg" },
  { id: "ana-sousa", name: "Drª Ana Sousa", role: { pt: "Higiene Oral", en: "Oral Hygiene" }, photo: "/team/ana-sousa.jpg" },
  { id: "catarina-leonardo", name: "Drª Catarina Leonardo", role: { pt: "Periodontologia", en: "Periodontology" }, photo: "/team/catarina-leonardo.jpg" },
  { id: "mariana-pires", name: "Drª Mariana Pires", role: { pt: "Endodontia", en: "Endodontics" }, photo: "/team/mariana-pires.jpg" },
  { id: "ines-mateus", name: "Drª Inês Mateus", role: { pt: "Odontopediatria", en: "Pediatric Dentistry" }, photo: "/team/ines-mateus.jpg" },
  { id: "rafaela-sacadura", name: "Drª Rafaela Sacadura", role: { pt: "Harmonização Facial", en: "Facial Harmonization" }, photo: "/team/rafaela-sacadura.jpg" },
  { id: "veronica-sousa-martins", name: "Drª Veronica Sousa Martins", role: { pt: "Periodontologia", en: "Periodontology" }, photo: "/team/veronica-sousa-martins.jpg" },
  { id: "tatiana-marques", name: "Drª Tatiana Marques", role: { pt: "Dentisteria", en: "Restorative Dentistry" }, photo: null as string | null },
] as const;

export const TREATMENTS = [
  { slug: "implantes", pt: "Implantes Dentários", en: "Dental Implants", img: "/treatments/implantes.jpg" },
  { slug: "protese-total-fixa", pt: "Prótese Total Fixa", en: "Full Fixed Prosthesis", img: "/treatments/protese-total-fixa.jpg" },
  { slug: "periodontologia", pt: "Periodontologia", en: "Periodontology", img: "/treatments/periodontologia.jpg" },
  { slug: "endodontia", pt: "Endodontia", en: "Endodontics", img: "/treatments/endodontia.jpg" },
  { slug: "invisalign", pt: "Invisalign®", en: "Invisalign®", img: "/treatments/invisalign.jpg" },
  { slug: "odontopediatria", pt: "Odontopediatria", en: "Pediatric Dentistry", img: "/treatments/odontopediatria.jpg" },
  { slug: "branqueamento", pt: "Branqueamento Dentário", en: "Teeth Whitening", img: "/treatments/branqueamento.jpg" },
  { slug: "facetas", pt: "Facetas Dentárias", en: "Dental Veneers", img: "/treatments/facetas.jpg" },
  { slug: "cirurgia-oral", pt: "Cirurgia Oral", en: "Oral Surgery", img: "/treatments/cirurgia-oral.jpg" },
  { slug: "dentisteria", pt: "Dentisteria Estética", en: "Aesthetic Dentistry", img: "/treatments/dentisteria.jpg" },
  { slug: "harmonizacao", pt: "Harmonização Facial", en: "Facial Harmonization", img: "/treatments/harmonizacao.jpg" },
  { slug: "gbt", pt: "Guided Biofilm Therapy ®", en: "Guided Biofilm Therapy ®", img: "/treatments/gbt.jpg" },
] as const;

export const CASE_PAIRS = [
  { before: "/cases/case-01.jpg", after: "/cases/case-02.jpg", label: { pt: "Caso clínico MD", en: "Clinical case MD" } },
  { before: "/cases/case-03.jpg", after: "/cases/case-04.jpg", label: { pt: "Caso clínico MD", en: "Clinical case MD" } },
  { before: "/cases/case-05.jpg", after: "/cases/case-06.jpg", label: { pt: "Caso clínico HF", en: "Clinical case HF" } },
] as const;

const pt = {
  brand: "LP CLINIC",
  brandLine: "Implantologia Oral & Estética Dentária",
  heroHeadline: "Redefina o seu sorriso\nrestaure a sua confiança",
  heroKicker: "Premium Dental Center",
  heroCta: "Marcar consulta",
  heroWhatsapp: "WhatsApp",
  chrome: {
    skip: "Saltar para o conteúdo",
    book: "Marcar",
    menu: "Menu",
    close: "Fechar",
    locale: "EN",
    localeAria: "Mudar para inglês",
    themeLight: "Modo claro",
    themeDark: "Modo escuro",
  },
  sobreTitle: "Sobre a clínica",
  sobreLead:
    "A LP CLINIC é uma clínica em Cascais especializada em implantologia complexa, Invisalign, facetas dentárias e estética facial — com um caminho claro para pacientes internacionais.",
  pillarsTitle: "Premium Dental Center",
  pillars: [
    { t: "EQUIPA ESPECIALIZADA", d: "Profissionais altamente qualificados e experientes em odontologia estética e implantologia avançada." },
    { t: "RESULTADOS NATURAIS E DURADOUROS", d: "Foco em procedimentos que proporcionam um sorriso natural e de longa duração." },
    { t: "EXCELÊNCIA EM IMPLANTOLOGIA", d: "Especialização em tratamentos de implantes dentários, oferecendo soluções avançadas para a substituição de dentes." },
    { t: "TECNOLOGIA", d: "Utilização de equipamentos modernos para garantir precisão e eficiência nos tratamentos." },
    { t: "AMBIENTE SEGURO", d: "Consultórios desenhados para proporcionar bem-estar e segurança aos pacientes." },
    { t: "FACILIDADE DE ACESSO", d: "Localizada em Cascais, com fácil acesso e estacionamento para conveniência dos pacientes." },
    { t: "ATENDIMENTO PERSONALIZADO", d: "Cada paciente recebe um plano de tratamento individualizado, com atenção aos detalhes e necessidades específicas." },
    { t: "QUALIDADE", d: "Uso de materiais de alta qualidade e técnicas comprovadas para melhores resultados." },
    { t: "REPUTAÇÃO E CONFIANÇA", d: "Reconhecida pelos pacientes pela qualidade e confiança nos serviços prestados." },
  ],
  treatmentsTitle: "Especialidades",
  treatmentsLead: "Tratamentos dentários avançados, personalizados e de alta qualidade.",
  journeyTitle: "O caminho do sorriso",
  journeyLead: "Consulta → Plano → Tratamento → Resultado",
  journey: [
    { t: "Consulta", d: "Primeiro contacto e avaliação clínica — presencial ou online para pacientes internacionais." },
    { t: "Plano", d: "Plano de tratamento individualizado com atenção aos detalhes e necessidades específicas." },
    { t: "Tratamento", d: "Procedimentos com tecnologia moderna — CBCT, scanner intraoral, CAD/CAM, Digital Smile Design." },
    { t: "Resultado", d: "Um sorriso natural e duradouro, com funcionalidade, estética e confiança restauradas." },
  ],
  techTitle: "Tecnologia",
  techLead: "Tecnologia dentária avançada: inovação ao serviço do seu sorriso.",
  tech: [
    { t: "Scanner Intraoral", d: "Moldes digitais sem desconforto — imagens de alta definição para planear e executar com precisão." },
    { t: "CBCT 3D", d: "Tomografia computorizada para diagnóstico dentário de alta precisão." },
    { t: "Sistema CAD/CAM", d: "Prótese dentária digital em tempo recorde — coroas, facetas e próteses com máxima precisão." },
    { t: "Sedação", d: "Sedação consciente e profunda para pacientes com ansiedade ou procedimentos complexos." },
    { t: "Guided Biofilm Therapy", d: "Limpeza dentária de alta performance com jato de ar, água e pó ultrafino." },
    { t: "Digital Smile Design", d: "Simulação do resultado final do tratamento estético antes de iniciar." },
  ],
  casesTitle: "Casos clínicos",
  casesLead:
    "Na LP CLINIC, acreditamos que cada sorriso tem uma história única para contar. Os casos clínicos refletem o nosso compromisso em transformar vidas através de tratamentos dentários avançados, personalizados e de alta qualidade.",
  casesHint: "Arraste ou passe o cursor para revelar o antes e depois.",
  before: "Antes",
  after: "Depois",
  teamTitle: "Equipa",
  teamLead: "Profissionais altamente qualificados em odontologia estética e implantologia avançada.",
  intlTitle: "Paciente internacional",
  intlLead:
    "Na LP CLINIC, temos o privilégio de receber não apenas pacientes locais, mas também pessoas vindas de várias partes do mundo.",
  intlWhyTitle: "Por que escolher a LP CLINIC como clínica dentária em Portugal?",
  intlWhy: [
    "Equipa clínica experiente e habituada a acompanhar pacientes internacionais",
    "Tecnologia avançada: CBCT, scanner intraoral, Digital Smile Design, sedação, CAD/CAM",
    "Tratamentos com resultados naturais e duradouros",
    "Localização acessível e central, com apoio em inglês e espanhol",
    "Possibilidade de tratamentos concentrados em menos consultas, adaptados à sua estadia",
  ],
  intlStepsTitle: "Como agendar a sua consulta internacional",
  intlSteps: [
    { t: "1. Primeiro contacto", d: "Envie-nos um e-mail para geral@lpclinic.pt ou use o formulário de marcação com nome, nacionalidade, tratamento pretendido e datas disponíveis." },
    { t: "2. Consulta online (opcional)", d: "Se necessário, agendamos uma consulta virtual com um dos nossos médicos dentistas." },
    { t: "3. Orçamento e plano de viagem", d: "Enviamos um plano estimado com valores, número de consultas e duração da estadia recomendada." },
    { t: "4. Confirmação e agendamento", d: "Com a confirmação, agendamos as consultas em blocos organizados para otimizar o tempo da sua estadia." },
  ],
  intlDock: "Paciente internacional",
  contactTitle: "Contacto & marcações",
  addressLabel: "Morada",
  address: "R. Pinheiros 192B\n2750-606 Cascais",
  hoursLabel: "Horários",
  hours: "Segunda a Sexta das 9h às 19h",
  contactsLabel: "Contactos",
  phones: ["(+351) 218 287 636", "(+351) 931 803 555"],
  email: "geral@lpclinic.pt",
  ersLabel: "ERS",
  ers: "Licença: 11464/2016 · Nº de Registo: E129481",
  disclaimer:
    "Estudo de design independente. Sem afiliação com a LP CLINIC. Copy e identidade públicos de lpclinic.pt.",
  builtBy: "built by dglxss",
  footerRights: "2015 LP CLINIC® | Cascais - Portugal",
};

const en: typeof pt = {
  brand: "LP CLINIC",
  brandLine: "Oral Implantology & Dental Aesthetics",
  heroHeadline: "Redefine your smile\nrestore your confidence",
  heroKicker: "Premium Dental Center",
  heroCta: "Book consultation",
  heroWhatsapp: "WhatsApp",
  chrome: {
    skip: "Skip to content",
    book: "Book",
    menu: "Menu",
    close: "Close",
    locale: "PT",
    localeAria: "Switch to Portuguese",
    themeLight: "Light mode",
    themeDark: "Dark mode",
  },
  sobreTitle: "About the clinic",
  sobreLead:
    "LP CLINIC is a Cascais clinic specialized in complex implantology, Invisalign, dental veneers, and facial aesthetics — with a clear path for international patients.",
  pillarsTitle: "Premium Dental Center",
  pillars: [
    { t: "SPECIALIZED TEAM", d: "Highly qualified and experienced professionals in aesthetic dentistry and advanced implantology." },
    { t: "NATURAL AND LONG-LASTING RESULTS", d: "Focus on procedures that provide a natural, long-lasting smile." },
    { t: "EXCELLENCE IN IMPLANTOLOGY", d: "Specializing in dental implant treatments, offering advanced solutions for tooth replacement." },
    { t: "TECHNOLOGY", d: "Use of modern equipment to ensure precision and efficiency in treatments." },
    { t: "SAFE ENVIRONMENT", d: "Offices designed to provide well-being and safety to patients." },
    { t: "EASE OF ACCESS", d: "Located in Cascais, with easy access and parking for the convenience of patients." },
    { t: "PERSONALIZED SERVICE", d: "Each patient receives an individualized treatment plan, with attention to detail and specific needs." },
    { t: "QUALITY", d: "Use of high quality materials and proven techniques for best results." },
    { t: "REPUTATION AND TRUST", d: "Recognized by patients for the quality and trust in the services provided." },
  ],
  treatmentsTitle: "Dental Treatments",
  treatmentsLead: "Advanced, personalized, high-quality dental treatments.",
  journeyTitle: "Smile journey",
  journeyLead: "Consultation → Plan → Treatment → Result",
  journey: [
    { t: "Consultation", d: "First contact and clinical assessment — in person or online for international patients." },
    { t: "Plan", d: "An individualized treatment plan with attention to detail and specific needs." },
    { t: "Treatment", d: "Procedures with modern technology — CBCT, intraoral scanner, CAD/CAM, Digital Smile Design." },
    { t: "Result", d: "A natural, lasting smile — function, aesthetics, and confidence restored." },
  ],
  techTitle: "Technology",
  techLead: "Advanced dental technology: innovation in service of your smile.",
  tech: [
    { t: "Intraoral Scanner", d: "Digital impressions without discomfort — high-definition images for precise planning." },
    { t: "CBCT 3D", d: "Cone-beam CT for high-precision dental diagnosis." },
    { t: "CAD/CAM System", d: "Digital prosthetics in record time — crowns, veneers, and prostheses with maximum precision." },
    { t: "Sedation", d: "Conscious and deep sedation for anxiety or complex procedures." },
    { t: "Guided Biofilm Therapy", d: "High-performance professional cleaning with air, water, and ultrafine powder." },
    { t: "Digital Smile Design", d: "Simulate the final aesthetic result before treatment begins." },
  ],
  casesTitle: "Clinical cases",
  casesLead:
    "At LP CLINIC, we believe that every smile has a unique story to tell. Clinical cases reflect our commitment to transforming lives through advanced, personalized, high-quality dental treatments.",
  casesHint: "Drag or hover to reveal before and after.",
  before: "Before",
  after: "After",
  teamTitle: "Our Team",
  teamLead: "Highly qualified professionals in aesthetic dentistry and advanced implantology.",
  intlTitle: "International patient",
  intlLead:
    "At LP CLINIC, we have the privilege of welcoming not only local patients, but also people from many parts of the world.",
  intlWhyTitle: "Why choose LP CLINIC as your dental clinic in Portugal?",
  intlWhy: [
    "Experienced clinical team accustomed to accompanying international patients",
    "Advanced technology: CBCT, intraoral scanner, Digital Smile Design, sedation, CAD/CAM",
    "Treatments with natural, long-lasting results",
    "Accessible central location, with support in English and Spanish",
    "Treatments concentrated in fewer visits, adapted to your stay",
  ],
  intlStepsTitle: "How to book your international consultation",
  intlSteps: [
    { t: "1. First contact", d: "Email geral@lpclinic.pt or use the booking form with your name, nationality, intended treatment, and available travel dates." },
    { t: "2. Online consultation (optional)", d: "If needed, we schedule a virtual consultation with one of our dentists." },
    { t: "3. Quote and travel plan", d: "We send an estimated treatment plan with values, number of visits, and recommended stay length." },
    { t: "4. Confirmation and scheduling", d: "Once confirmed, we book appointments in organized blocks to optimize your stay." },
  ],
  intlDock: "International patient",
  contactTitle: "Contact & bookings",
  addressLabel: "Address",
  address: "R. Pinheiros 192B\n2750-606 Cascais",
  hoursLabel: "Hours",
  hours: "Monday to Friday from 9am to 7pm",
  contactsLabel: "Contacts",
  phones: ["(+351) 218 287 636", "(+351) 931 803 555"],
  email: "geral@lpclinic.pt",
  ersLabel: "ERS",
  ers: "License: 11464/2016 · Registration: E129481",
  disclaimer:
    "Independent design study. Not affiliated with LP CLINIC. Public copy and identity from lpclinic.pt.",
  builtBy: "built by dglxss",
  footerRights: "2015 LP CLINIC® | Cascais - Portugal",
};

export const dictionaries = { pt, en };
