export type Locale = "pt" | "en";
export type Theme = "dark" | "light";

export type Dictionary = typeof dictionaries.pt;

export const links = {
  booking: "https://www.lpclinic.pt/marcacoes-online",
  whatsapp: "https://wa.me/351931803555",
  email: "mailto:geral@lpclinic.pt",
  phonePrimary: "tel:+351218287636",
  phoneSecondary: "tel:+351931803555",
  maps: "https://www.google.com/maps/search/?api=1&query=R.+Pinheiros+192B+2750-606+Cascais",
  instagram: "https://www.instagram.com/lpclinic_pt/",
  facebook: "https://www.facebook.com/lpclinicpt/",
  tiktok: "https://www.tiktok.com/@lpclinic_pt",
  dglxss: "https://dglxss.com",
  original: "https://www.lpclinic.pt/",
};

export const RAIL = [
  { id: "sobre", pt: "Sobre", en: "About" },
  { id: "tratamentos", pt: "Tratamentos", en: "Treatments" },
  { id: "tecnologia", pt: "Tecnologia", en: "Technology" },
  { id: "casos", pt: "Casos", en: "Cases" },
  { id: "equipa", pt: "Equipa", en: "Team" },
  { id: "internacional", pt: "Internacional", en: "International" },
  { id: "contacto", pt: "Contacto", en: "Contact" },
] as const;

export const TEAM = [
  { id: "pedro-pimenta", name: "Dr. Pedro Pimenta", role: { pt: "Cirurgia | Reabilitação Oral", en: "Surgery | Oral Rehabilitation" }, photo: "/team/pedro-pimenta.jpg", detail: { pt: "OMD 9911. Invisalign, facetas e reabilitação com implantes, publicados pela clínica.", en: "OMD 9911. Invisalign, veneers, and implant rehabilitation published by the clinic." } },
  { id: "catarina-cardoso", name: "Drª Catarina Cardoso", role: { pt: "Harmonização Facial", en: "Facial Harmonization" }, photo: "/team/catarina-cardoso.jpg", detail: { pt: "A avaliação vem primeiro. Recusa procedimentos de medicina estética que não fazem sentido.", en: "Assessment comes first. She declines aesthetic procedures that are not indicated." } },
  { id: "mafalda-faria", name: "Drª Mafalda Faria", role: { pt: "Generalista", en: "General Dentistry" }, photo: "/team/mafalda-faria.jpg", detail: { pt: "Clínica geral e prevenção — o dia a dia da saúde oral na LP CLINIC.", en: "General dentistry and prevention — everyday oral health at LP CLINIC." } },
  { id: "ana-sousa", name: "Drª Ana Sousa", role: { pt: "Higiene Oral", en: "Oral Hygiene" }, photo: "/team/ana-sousa.jpg", detail: { pt: "Cédula C-036332089. Higiene com protocolo GBT: ar, água e pó ultrafino.", en: "License C-036332089. Hygiene with the GBT protocol: air, water, and ultrafine powder." } },
  { id: "catarina-leonardo", name: "Drª Catarina Leonardo", role: { pt: "Periodontologia", en: "Periodontology" }, photo: "/team/catarina-leonardo.jpg", detail: { pt: "Periodontologia e branqueamento Philips Zoom — domiciliário, em clínica ou misto.", en: "Periodontology and Philips Zoom whitening — at home, in clinic, or combined." } },
  { id: "mariana-pires", name: "Drª Mariana Pires", role: { pt: "Endodontia", en: "Endodontics" }, photo: "/team/mariana-pires.jpg", detail: { pt: "Endodontia. Depois do tratamento, a coroa pode proteger dentes muito desgastados.", en: "Endodontics. After treatment, a crown can protect a heavily worn tooth." } },
  { id: "ines-mateus", name: "Drª Inês Mateus", role: { pt: "Odontopediatria", en: "Pediatric Dentistry" }, photo: "/team/ines-mateus.jpg", detail: { pt: "Odontopediatria na LP CLINIC, em Cascais.", en: "Pediatric dentistry at LP CLINIC, in Cascais." } },
  { id: "rafaela-sacadura", name: "Drª Rafaela Sacadura", role: { pt: "Harmonização Facial", en: "Facial Harmonization" }, photo: "/team/rafaela-sacadura.jpg", detail: { pt: "Harmonização facial na mesma linha clínica: natural, sem procedimentos desnecessários.", en: "Facial harmonization on the same clinical line: natural, without unnecessary procedures." } },
  { id: "veronica-sousa-martins", name: "Drª Veronica Sousa Martins", role: { pt: "Periodontologia", en: "Periodontology" }, photo: "/team/veronica-sousa-martins.jpg", detail: { pt: "Gengiva e osso de suporte. O mau hálito, muitas vezes, começa aqui — não na escova.", en: "Gums and supporting bone. Bad breath often starts here, not with the toothbrush." } },
  { id: "tatiana-marques", name: "Drª Tatiana Marques", role: { pt: "Dentisteria", en: "Restorative Dentistry" }, photo: null as string | null, detail: { pt: "Dentisteria estética na equipa publicada da LP CLINIC.", en: "Aesthetic dentistry on the published LP CLINIC team." } },
] as const;

export const TREATMENTS = [
  { slug: "implantes", pt: "Implantes Dentários", en: "Dental Implants", img: "/treatments/implantes.jpg", href: "https://www.lpclinic.pt/implantes-dentarios", detail: { pt: "Planeamento 3D e cirurgia guiada por CBCT. Reabilitação fixa quando a periodontite já comprometeu os dentes.", en: "3D planning and CBCT-guided surgery. Fixed rehabilitation when periodontitis has already compromised the teeth." } },
  { slug: "protese-total-fixa", pt: "Prótese Total Fixa", en: "Full Fixed Prosthesis", img: "/treatments/protese-total-fixa.jpg", href: "https://www.lpclinic.pt/protese-total-fixa", detail: { pt: "Coroas unitárias sobre dentes e implantes. Em muitos casos CAD/CAM, a reabilitação pode ser no próprio dia.", en: "Individual crowns on teeth and implants. With CAD/CAM, rehabilitation can often be done the same day." } },
  { slug: "periodontologia", pt: "Periodontologia", en: "Periodontology", img: "/treatments/periodontologia.jpg", href: "https://www.lpclinic.pt/periodontologia", detail: { pt: "Gengivite, periodontite e sangramento. O mau hálito trata-se na causa, não só na escova.", en: "Gingivitis, periodontitis, and bleeding. Bad breath is treated at the cause, not only with brushing." } },
  { slug: "endodontia", pt: "Endodontia", en: "Endodontics", img: "/treatments/endodontia.jpg", href: "https://www.lpclinic.pt/endodontia", detail: { pt: "Microscópio no consultório. Após a endodontia, a coroa protege dentes muito desgastados e devolve função.", en: "A microscope in the operatory. After root canal treatment, a crown protects a worn tooth and restores function." } },
  { slug: "invisalign", pt: "Invisalign®", en: "Invisalign®", img: "/treatments/invisalign.jpg", href: "https://www.lpclinic.pt/ortodontia", detail: { pt: "Alinhadores transparentes com scanner intraoral. O Dr. Pedro Pimenta (OMD 9911) publica os casos na clínica.", en: "Clear aligners with an intraoral scanner. Dr. Pedro Pimenta (OMD 9911) publishes cases from the clinic." } },
  { slug: "odontopediatria", pt: "Odontopediatria", en: "Pediatric Dentistry", img: "/treatments/odontopediatria.jpg", href: "https://www.lpclinic.pt/odontopediatria", detail: { pt: "Consultas com a Drª Inês Mateus. A anestesia da clínica é pensada para ser curta — e indolor.", en: "Visits with Dr. Inês Mateus. Anesthesia at the clinic is planned to be brief — and painless." } },
  { slug: "branqueamento", pt: "Branqueamento Dentário", en: "Teeth Whitening", img: "/treatments/branqueamento.jpg", href: "https://www.lpclinic.pt/branqueamento-dentario", detail: { pt: "Domiciliário, em clínica ou misto. Philips Zoom com a Drª Catarina Leonardo: luminosidade natural, não um sorriso artificial.", en: "At home, in clinic, or combined. Philips Zoom with Dr. Catarina Leonardo: natural luminosity, not an artificial smile." } },
  { slug: "facetas", pt: "Facetas Dentárias", en: "Dental Veneers", img: "/treatments/facetas.jpg", href: "https://www.lpclinic.pt/facetas-dentarias", detail: { pt: "Primeiro o alinhamento, depois facetas. Um caso publicado usou 4 facetas nos incisivos, pelo Dr. Pedro Pimenta.", en: "Alignment first, then veneers. One published case used 4 incisor veneers, by Dr. Pedro Pimenta." } },
  { slug: "cirurgia-oral", pt: "Cirurgia Oral", en: "Oral Surgery", img: "/treatments/cirurgia-oral.jpg", href: "https://www.lpclinic.pt/cirurgia-oral", detail: { pt: "Extrações e cirurgia guiada por CBCT, com a equipa de cirurgia e reabilitação oral.", en: "Extractions and CBCT-guided surgery, with the oral surgery and rehabilitation team." } },
  { slug: "dentisteria", pt: "Dentisteria Estética", en: "Aesthetic Dentistry", img: "/treatments/dentisteria.jpg", href: "https://www.lpclinic.pt/dentisteria", detail: { pt: "Cáries, desgaste e o dente natural. A clínica trabalha zircónia, dissilicato de lítio e compósito — o material faz parte do plano.", en: "Caries, wear, and the natural tooth. The clinic works in zirconia, lithium disilicate, and composite — the material is part of the plan." } },
  { slug: "harmonizacao", pt: "Harmonização Facial", en: "Facial Harmonization", img: "/treatments/harmonizacao.jpg", href: "https://www.lpclinic.pt/harmonizacao-facial", detail: { pt: "Drª Catarina Cardoso. Toxina botulínica e bioestimuladores só depois da avaliação — e há casos em que a resposta é não.", en: "Dr. Catarina Cardoso. Botulinum toxin and biostimulators only after assessment — and sometimes the answer is no." } },
  { slug: "gbt", pt: "Guided Biofilm Therapy ®", en: "Guided Biofilm Therapy ®", img: "/treatments/gbt.jpg", href: "https://www.lpclinic.pt/gbt", detail: { pt: "Protocolo GBT com a Drª Ana Sousa. Jato de ar, água e pó ultrafino, pensado para implantes, ortodontia e sensibilidade.", en: "GBT protocol with Dr. Ana Sousa. Air, water, and ultrafine powder, planned for implants, orthodontics, and sensitivity." } },
] as const;

export const CASE_PAIRS = [
  {
    before: "/cases/case-01.jpg",
    after: "/cases/case-02.jpg",
    href: "https://www.lpclinic.pt/casos-clinicos-md",
    label: { pt: "Caso clínico MD", en: "Clinical case MD" },
    detail: {
      pt: "Caso de medicina dentária publicado. O antes e o depois mostram função e estética, sem um resultado inventado.",
      en: "Published dentistry case. The before and after show function and aesthetics, not an invented result.",
    },
  },
  {
    before: "/cases/case-03.jpg",
    after: "/cases/case-04.jpg",
    href: "https://www.lpclinic.pt/casos-clinicos-md",
    label: { pt: "Caso clínico MD", en: "Clinical case MD" },
    detail: {
      pt: "Segundo caso MD do arquivo publicado. Arraste o revelador para comparar o registo clínico.",
      en: "Second MD case from the published archive. Drag the reveal to compare the clinical record.",
    },
  },
  {
    before: "/cases/case-05.jpg",
    after: "/cases/case-06.jpg",
    href: "https://www.lpclinic.pt/casos-clinicos-hf",
    label: { pt: "Caso clínico HF", en: "Clinical case HF" },
    detail: {
      pt: "Caso de harmonização facial publicado. A comparação fica no registo da clínica, não numa simulação.",
      en: "Published facial-harmonization case. The comparison stays with the clinic record, not a simulation.",
    },
  },
] as const;

const pt = {
  brand: "LP CLINIC",
  brandLine: "Implantologia Oral & Estética Dentária",
  heroHeadline: "Redefina o seu sorriso\nrestaure a sua confiança",
  heroKicker: "Premium Dental Center",
  heroPhotoAlt: "Sorriso publicado pela LP CLINIC",
  heroCta: "Marcar consulta",
  heroWhatsapp: "WhatsApp",
  instagramKicker: "Instagram",
  instagramAccount: "@lpclinic_pt",
  instagramLead:
    "Vinte e três publicações recentes da clínica — casos, equipa e o consultório em Cascais. As imagens estão no site; o link abre o post.",
  instagramOpen: "Abrir no Instagram",
  instagramFeed: "Publicações públicas recentes da LP CLINIC no Instagram",
  chrome: {
    skip: "Saltar para o conteúdo",
    book: "Marcar",
    menu: "Menu",
    close: "Fechar",
    locale: "EN",
    localeAria: "Mudar para inglês",
    themeLight: "Modo claro",
    themeDark: "Modo escuro",
  },
  sobreTitle: "Sobre a clínica",
  sobreLead:
    "A LP CLINIC é uma clínica em Cascais especializada em implantologia complexa, Invisalign, facetas dentárias e estética facial — com um caminho claro para pacientes internacionais.",
  pillarsTitle: "Premium Dental Center",
  pillars: [
    { t: "EQUIPA ESPECIALIZADA", d: "Profissionais altamente qualificados e experientes em odontologia estética e implantologia avançada.", img: "/team/pedro-pimenta.jpg" },
    { t: "RESULTADOS NATURAIS E DURADOUROS", d: "Foco em procedimentos que proporcionam um sorriso natural e de longa duração.", img: "/treatments/facetas.jpg" },
    { t: "EXCELÊNCIA EM IMPLANTOLOGIA", d: "Especialização em tratamentos de implantes dentários, oferecendo soluções avançadas para a substituição de dentes.", img: "/clinic/allonx.jpg" },
    { t: "TECNOLOGIA", d: "Utilização de equipamentos modernos para garantir precisão e eficiência nos tratamentos.", img: "/clinic/microscope.jpg" },
    { t: "AMBIENTE SEGURO", d: "Consultórios desenhados para proporcionar bem-estar e segurança aos pacientes.", img: "/clinic/operatory.jpg" },
    { t: "FACILIDADE DE ACESSO", d: "R. Pinheiros 192B, Cascais — acesso fácil e estacionamento para quem vem de carro.", img: "/clinic/exterior.jpg" },
    { t: "ATENDIMENTO PERSONALIZADO", d: "Cada paciente recebe um plano de tratamento individualizado, com atenção aos detalhes e necessidades específicas.", img: "/clinic/consult.jpg" },
    { t: "QUALIDADE", d: "Zircónia, dissilicato de lítio ou compósito: o material entra no plano, não fica só no slogan.", img: "/clinic/bonding.jpg" },
    { t: "REPUTAÇÃO E CONFIANÇA", d: "Reconhecida pelos pacientes pela qualidade e confiança nos serviços prestados.", img: "/treatments/branqueamento.jpg" },
  ],
  treatmentsTitle: "Especialidades",
  treatmentsLead: "Tratamentos dentários avançados, personalizados e de alta qualidade.",
  journeyTitle: "O caminho do sorriso",
  journeyLead: "Consulta → Plano → Tratamento → Resultado",
  journey: [
    { t: "Consulta", d: "Primeiro contacto e avaliação clínica — presencial na R. Pinheiros ou online para quem vem de fora.", img: "/clinic/consult.jpg" },
    { t: "Plano", d: "Plano individualizado: scanner intraoral, Digital Smile Design e, quando faz falta, CBCT.", img: "/clinic/aligners.jpg" },
    { t: "Tratamento", d: "No consultório: implantes, facetas, Invisalign, GBT, sedação. Blocos de consultas se a estadia for curta.", img: "/clinic/operatory.jpg" },
    { t: "Resultado", d: "Função, estética e confiança. Os casos publicados ficam no arquivo clínico — não numa simulação.", img: "/treatments/protese-total-fixa.jpg" },
  ],
  techTitle: "Tecnologia",
  techLead: "Tecnologia dentária avançada: inovação ao serviço do seu sorriso.",
  tech: [
    { t: "Scanner Intraoral", d: "Substitui o molde tradicional. Facetas, Invisalign, coroas e próteses planeiam-se em imagem de alta definição.", img: "/clinic/operatory-detail.jpg" },
    { t: "CBCT 3D", d: "Tomografia de feixe cónico para implantes, cirurgia e endodontia — diagnóstico tridimensional antes de tocar no dente.", img: "/clinic/allonx.jpg" },
    { t: "Sistema CAD/CAM", d: "Coroas, facetas e próteses desenhadas em digital. Em muitos casos, a reabilitação pode ser no próprio dia.", img: "/treatments/protese-total-fixa.jpg" },
    { t: "Sedação", d: "Consciente, profunda ou anestesia geral, para ansiedade ou procedimentos longos. Feita por profissionais experientes.", img: "/clinic/operatory-chair.jpg" },
    { t: "Guided Biofilm Therapy", d: "Ar, água e pó ultrafino. Indicada com implantes, ortodontia ou sensibilidade — menos invasiva que a destartarização clássica.", img: "/clinic/gbt.jpg" },
    { t: "Digital Smile Design", d: "Fotos, vídeo e modelo digital para ver o sorriso estético antes de começar. O plano fica previsível.", img: "/treatments/facetas.jpg" },
  ],
  casesTitle: "Casos clínicos",
  casesLead:
    "Na LP CLINIC, acreditamos que cada sorriso tem uma história única para contar. Os casos clínicos refletem o nosso compromisso em transformar vidas através de tratamentos dentários avançados, personalizados e de alta qualidade.",
  casesHint: "Arraste, ou use as setas do teclado, para revelar o antes e depois.",
  casesOpen: "Ver no site da clínica",
  before: "Antes",
  after: "Depois",
  teamTitle: "Equipa",
  teamLead: "Profissionais altamente qualificados em odontologia estética e implantologia avançada.",
  intlTitle: "Paciente internacional",
  intlLead:
    "Na LP CLINIC, temos o privilégio de receber não apenas pacientes locais, mas também pessoas vindas de várias partes do mundo.",
  intlWhyTitle: "Por que escolher a LP CLINIC como clínica dentária em Portugal?",
  intlWhy: [
    { t: "Equipa habituada a quem vem de fora", d: "Pacientes da Europa, América, África e Médio Oriente. O acompanhamento é o mesmo plano clínico, na língua que preferir.", img: "/team/mafalda-faria.jpg" },
    { t: "Tecnologia no plano, não na brochura", d: "CBCT, scanner intraoral, Digital Smile Design, sedação e CAD/CAM — o que permite fechar etapas na mesma estadia.", img: "/clinic/operatory-detail.jpg" },
    { t: "Resultados naturais", d: "A clínica descreve os casos como função, estética e confiança. Sem um sorriso de catálogo inventado para o anúncio.", img: "/treatments/invisalign.jpg" },
    { t: "Cascais, com inglês e espanhol", d: "R. Pinheiros 192B. Toda a equipa comunica em português, inglês e espanhol.", img: "/clinic/exterior.jpg" },
    { t: "Menos consultas, se for viável", d: "Quando é clinicamente possível, o scanner e o CAD/CAM concentram o tratamento em menos visitas.", img: "/clinic/operatory-chair.jpg" },
  ],
  intlStepsTitle: "Como agendar a sua consulta internacional",
  intlSteps: [
    { t: "1. Primeiro contacto", d: "Email geral@lpclinic.pt ou o formulário: nome, nacionalidade, tratamento (facetas, implantes, Invisalign, reabilitação), datas, idioma e radiografias se já as tiver.", img: "/clinic/consult.jpg" },
    { t: "2. Consulta online (opcional)", d: "Se o caso pedir, há uma consulta virtual com um médico dentista da equipa antes de viajar.", img: "/team/catarina-cardoso.jpg" },
    { t: "3. Orçamento e plano de viagem", d: "Plano estimado com valores, número de consultas e dias em Cascais. Alojamento e transporte, se quiser indicação.", img: "/clinic/aligners.jpg" },
    { t: "4. Confirmação e agendamento", d: "As consultas entram em blocos, para a estadia não se gastar à espera entre sessões.", img: "/treatments/protese-total-fixa.jpg" },
  ],
  intlFaqTitle: "Perguntas de quem viaja",
  intlFaq: [
    { q: "Dá para fazer tudo numa viagem?", a: "Sim, quando é clinicamente viável. O scanner e o CAD/CAM encurtam etapas que, noutro sítio, pediriam mais deslocações.", img: "/clinic/operatory.jpg" },
    { q: "Que pagamentos aceitam?", a: "Transferência bancária, cartão de crédito e MbWay. Os dados seguem com o plano de tratamento.", img: "/clinic/bonding.jpg" },
    { q: "Ajudam com estadia?", a: "Podem indicar alojamento perto da clínica, transporte e parcerias com motoristas privados.", img: "/clinic/exterior.jpg" },
    { q: "Que línguas se falam?", a: "Português, inglês e espanhol — em toda a equipa, não só na receção.", img: "/team/ana-sousa.jpg" },
  ],
  intlDock: "Paciente internacional",
  contactTitle: "Contacto & marcações",
  addressLabel: "Morada",
  address: "R. Pinheiros 192B\n2750-606 Cascais",
  hoursLabel: "Horários",
  hours: "Segunda a Sexta das 9h às 19h",
  contactsLabel: "Contactos",
  phones: ["(+351) 218 287 636", "(+351) 931 803 555"],
  email: "geral@lpclinic.pt",
  ersLabel: "ERS",
  ers: "Licença: 11464/2016 · Nº de Registo: E129481",
  disclaimer:
    "Estudo de design independente. Sem afiliação com a LP CLINIC. Copy e identidade públicos de lpclinic.pt.",
  builtBy: "built by dglxss",
  footerRights: "2015 LP CLINIC® | Cascais - Portugal",
};

const en: typeof pt = {
  brand: "LP CLINIC",
  brandLine: "Oral Implantology & Dental Aesthetics",
  heroHeadline: "Redefine your smile\nrestore your confidence",
  heroKicker: "Premium Dental Center",
  heroPhotoAlt: "Smile published by LP CLINIC",
  heroCta: "Book consultation",
  heroWhatsapp: "WhatsApp",
  instagramKicker: "Instagram",
  instagramAccount: "@lpclinic_pt",
  instagramLead:
    "Twenty-three recent posts from the clinic — cases, the team, and the Cascais operatory. Images live on this site; the link opens the post.",
  instagramOpen: "Open on Instagram",
  instagramFeed: "Recent public posts from LP CLINIC on Instagram",
  chrome: {
    skip: "Skip to content",
    book: "Book",
    menu: "Menu",
    close: "Close",
    locale: "PT",
    localeAria: "Switch to Portuguese",
    themeLight: "Light mode",
    themeDark: "Dark mode",
  },
  sobreTitle: "About the clinic",
  sobreLead:
    "LP CLINIC is a Cascais clinic specialized in complex implantology, Invisalign, dental veneers, and facial aesthetics — with a clear path for international patients.",
  pillarsTitle: "Premium Dental Center",
  pillars: [
    { t: "SPECIALIZED TEAM", d: "Highly qualified and experienced professionals in aesthetic dentistry and advanced implantology.", img: "/team/pedro-pimenta.jpg" },
    { t: "NATURAL AND LONG-LASTING RESULTS", d: "Focus on procedures that provide a natural, long-lasting smile.", img: "/treatments/facetas.jpg" },
    { t: "EXCELLENCE IN IMPLANTOLOGY", d: "Specializing in dental implant treatments, offering advanced solutions for tooth replacement.", img: "/clinic/allonx.jpg" },
    { t: "TECHNOLOGY", d: "Use of modern equipment to ensure precision and efficiency in treatments.", img: "/clinic/microscope.jpg" },
    { t: "SAFE ENVIRONMENT", d: "Operatories designed for comfort and safety.", img: "/clinic/operatory.jpg" },
    { t: "EASE OF ACCESS", d: "R. Pinheiros 192B, Cascais — easy access and parking if you are driving.", img: "/clinic/exterior.jpg" },
    { t: "PERSONALIZED SERVICE", d: "Each patient receives an individualized treatment plan, with attention to detail and specific needs.", img: "/clinic/consult.jpg" },
    { t: "QUALITY", d: "Zirconia, lithium disilicate, or composite: the material is part of the plan, not a slogan.", img: "/clinic/bonding.jpg" },
    { t: "REPUTATION AND TRUST", d: "Recognized by patients for the quality and trust in the services provided.", img: "/treatments/branqueamento.jpg" },
  ],
  treatmentsTitle: "Dental Treatments",
  treatmentsLead: "Advanced, personalized, high-quality dental treatments.",
  journeyTitle: "Smile journey",
  journeyLead: "Consultation → Plan → Treatment → Result",
  journey: [
    { t: "Consultation", d: "First contact and clinical assessment — in person on R. Pinheiros, or online if you are traveling in.", img: "/clinic/consult.jpg" },
    { t: "Plan", d: "An individual plan: intraoral scanner, Digital Smile Design, and CBCT when the case needs it.", img: "/clinic/aligners.jpg" },
    { t: "Treatment", d: "In the operatory: implants, veneers, Invisalign, GBT, sedation. Visits are blocked together if your stay is short.", img: "/clinic/operatory.jpg" },
    { t: "Result", d: "Function, aesthetics, and confidence. Published cases stay in the clinical archive — not a mock-up.", img: "/treatments/protese-total-fixa.jpg" },
  ],
  techTitle: "Technology",
  techLead: "Advanced dental technology: innovation in service of your smile.",
  tech: [
    { t: "Intraoral Scanner", d: "Replaces the traditional impression. Veneers, Invisalign, crowns, and prostheses are planned from high-definition images.", img: "/clinic/operatory-detail.jpg" },
    { t: "CBCT 3D", d: "Cone-beam CT for implants, surgery, and endodontics — a three-dimensional diagnosis before the tooth is touched.", img: "/clinic/allonx.jpg" },
    { t: "CAD/CAM System", d: "Crowns, veneers, and prostheses designed digitally. In many cases rehabilitation can be done the same day.", img: "/treatments/protese-total-fixa.jpg" },
    { t: "Sedation", d: "Conscious, deep, or general anesthesia for anxiety or long procedures. Delivered by experienced clinicians.", img: "/clinic/operatory-chair.jpg" },
    { t: "Guided Biofilm Therapy", d: "Air, water, and ultrafine powder. Planned for implants, orthodontics, or sensitivity — less invasive than classic scaling.", img: "/clinic/gbt.jpg" },
    { t: "Digital Smile Design", d: "Photos, video, and a digital model so you can see the aesthetic smile before it starts. The plan stays predictable.", img: "/treatments/facetas.jpg" },
  ],
  casesTitle: "Clinical cases",
  casesLead:
    "At LP CLINIC, we believe that every smile has a unique story to tell. Clinical cases reflect our commitment to transforming lives through advanced, personalized, high-quality dental treatments.",
  casesHint: "Drag, or use the arrow keys, to reveal before and after.",
  casesOpen: "View on the clinic site",
  before: "Before",
  after: "After",
  teamTitle: "Our Team",
  teamLead: "Highly qualified professionals in aesthetic dentistry and advanced implantology.",
  intlTitle: "International patient",
  intlLead:
    "At LP CLINIC, we have the privilege of welcoming not only local patients, but also people from many parts of the world.",
  intlWhyTitle: "Why choose LP CLINIC as your dental clinic in Portugal?",
  intlWhy: [
    { t: "A team used to people who fly in", d: "Patients from Europe, the Americas, Africa, and the Middle East. The clinical plan is the same, in the language you prefer.", img: "/team/mafalda-faria.jpg" },
    { t: "Technology in the plan, not the brochure", d: "CBCT, intraoral scanner, Digital Smile Design, sedation, and CAD/CAM — what makes it possible to close stages in one stay.", img: "/clinic/operatory-detail.jpg" },
    { t: "Natural results", d: "The clinic describes cases as function, aesthetics, and confidence. Not a catalogue smile invented for an ad.", img: "/treatments/invisalign.jpg" },
    { t: "Cascais, in English and Spanish", d: "R. Pinheiros 192B. The whole team speaks Portuguese, English, and Spanish.", img: "/clinic/exterior.jpg" },
    { t: "Fewer visits, when it is viable", d: "When it is clinically possible, the scanner and CAD/CAM concentrate treatment into fewer appointments.", img: "/clinic/operatory-chair.jpg" },
  ],
  intlStepsTitle: "How to book your international consultation",
  intlSteps: [
    { t: "1. First contact", d: "Email geral@lpclinic.pt or the form: name, nationality, treatment (veneers, implants, Invisalign, full rehab), dates, language, and radiographs if you already have them.", img: "/clinic/consult.jpg" },
    { t: "2. Online consultation (optional)", d: "If the case needs it, a virtual visit with one of the dentists happens before you travel.", img: "/team/catarina-cardoso.jpg" },
    { t: "3. Quote and travel plan", d: "An estimated plan with fees, number of visits, and days in Cascais. Lodging and transport, if you want a suggestion.", img: "/clinic/aligners.jpg" },
    { t: "4. Confirmation and scheduling", d: "Appointments are blocked together so the stay is not spent waiting between sessions.", img: "/treatments/protese-total-fixa.jpg" },
  ],
  intlFaqTitle: "Questions from people who travel",
  intlFaq: [
    { q: "Can it all happen in one trip?", a: "Yes, when it is clinically viable. The scanner and CAD/CAM shorten stages that would otherwise mean more travel.", img: "/clinic/operatory.jpg" },
    { q: "Which payments do you take?", a: "Bank transfer, credit card, and MbWay. The details travel with the treatment plan.", img: "/clinic/bonding.jpg" },
    { q: "Help with the stay?", a: "They can suggest lodging near the clinic, transport, and private-driver partners.", img: "/clinic/exterior.jpg" },
    { q: "Which languages?", a: "Portuguese, English, and Spanish — across the team, not only at reception.", img: "/team/ana-sousa.jpg" },
  ],
  intlDock: "International patient",
  contactTitle: "Contact & bookings",
  addressLabel: "Address",
  address: "R. Pinheiros 192B\n2750-606 Cascais",
  hoursLabel: "Hours",
  hours: "Monday to Friday from 9am to 7pm",
  contactsLabel: "Contacts",
  phones: ["(+351) 218 287 636", "(+351) 931 803 555"],
  email: "geral@lpclinic.pt",
  ersLabel: "ERS",
  ers: "License: 11464/2016 · Registration: E129481",
  disclaimer:
    "Independent design study. Not affiliated with LP CLINIC. Public copy and identity from lpclinic.pt.",
  builtBy: "built by dglxss",
  footerRights: "2015 LP CLINIC® | Cascais - Portugal",
};

export const dictionaries = { pt, en };
